### ISSUE TITLE
I am very happy that I am the first question.i need help

### ISSUE THREAD

**Issue by FindFabricFaith** [go-micro/cli#1]
in win10
run `go install go-micro.dev/v4/cmd/micro@master`
but get message 
`go install go-micro.dev/v4/cmd/micro@master: module go-micro.dev/v4@master found (v4.6.1-0.20220407104607-62c2981baf63), but does not contain package go-micro.dev/v4/cmd/micro`

**Comment by Scorpio69t** [comment]
I got this error too

**Comment by abrahamSN** [comment]
I got this error too

**Comment by abrahamSN** [comment]
I just install the previous version. and it solves my problems.
`go install go-micro.dev/v4/cmd/micro@v4.6.0 `

**Comment by Davincible** [comment]
You can now install with
```bash
go install github.com/go-micro/cli/cmd/go-micro@latest
```
