### ISSUE TITLE
flag provided but not defined: -o when run 

### ISSUE THREAD

**Issue by umuoy1** [go-micro/cli#3]
Go version: 1.18.2
Platform: Linux

I ran
`go install -o go-micro github.com/go-micro/cli`
but I got
`flag provided but not defined: -o`

**Comment by asim** [comment]
Should be `go build`

**Comment by Mistic92** [comment]
Same issue, `go build` is not changing anything

**Comment by Davincible** [comment]
You can now install with
```bash
go install github.com/go-micro/cli/cmd/go-micro@latest
```
