### ISSUE TITLE
Can't find protoc-gen-micro plugin for go micro v4

### ISSUE THREAD

**Issue by agsimfzi** [go-micro/cli#7]
When i run `go install go-micro.dev/v4/cmd/protoc-gen-micro@v4`
i got an error like this `go: go-micro.dev/v4/cmd/protoc-gen-micro@v4: module go-micro.dev/v4@v4 found (v4.8.0), but does not contain package go-micro.dev/v4/cmd/protoc-gen-micro`

**Comment by xpunch** [comment]
```
go install github.com/go-micro/generator/cmd/protoc-gen-micro@latest
```

**Comment by agsimfzi** [comment]
oke thanks

**Comment by xpunch** [comment]
https://github.com/asim/go-micro/issues/2526
