### ISSUE TITLE
github.com/micro/cli/v2@v2.1.2 404 Not Found

### ISSUE THREAD

**Issue by jclivi** [go-micro/cli#8]
![2022-09-07_17-40](https://user-images.githubusercontent.com/14210650/188846484-7aa4ecf7-aa88-4370-9390-008770ff3f84.png)

**Comment by Davincible** [comment]
You need the CLI from this repo, github.com/micro doesn't host the CLI anymore.

Also, you are using github.com/micro/micro, not github.com/asim/go-micro, which is the project this org is about

**Comment by jclivi** [comment]
@Davincible 
thanks ！

**Comment by yb19890724** [comment]
![image](https://user-images.githubusercontent.com/21005459/191011372-e2d11241-c8d3-49b0-be66-92445fc8760b.png)
please  How can I solve it ???

**Comment by Davincible** [comment]
@yb19890724  You're using micro v3, upgrade to the latest v4

**Comment by jclivi** [comment]
@yb19890724 
export GOPROXY=https://goproxy.io,direct
